import 'dart:math';

class Category {
  int _index;
  String _language;
  Set<String> _set = {};
  Category(this._index, this._language);

  final _categories = {
    'es_ES': [
      [
        'trompeta',
        'martillo',
        'leche',
        'mecedora',
        'cohete',
        'avión',
        'escalera',
        'despertador',
        'disco',
        'lonchera',
        'pies',
        'piano',
        'sal',
        'guitarra',
        'ambulancia',
        'hombro',
        'carro',
        'bebé',
        'pulsera',
        'carro de mercado',
        'engrapadora',
        'cepillo',
        'tijera',
        'cabello',
        'pelota',
        'flauta',
        'pijamas',
        'lluvia',
        'terremoto',
        'nariz',
        'cono de helado',
        'lentes',
        'oido',
        'bomba',
        'banana',
        'sombrero',
        'mesa de planchar',
        'porrista',
        'reloj',
        'secador de cabello',
        'dinero',
        'silla',
        'teléfono',
        'cornetas',
        'brazo',
        'pala',
        'fuego',
        'paleta',
        'tambor',
        'tenedor',
      ],
      [
        'la sirenita',
        'el gato con botas',
        'ricitos de oro',
        'hércules',
        'el rey león',
        'superman',
        'cenicienta',
        'dumbo',
        'mi pobre angelito',
        'pinocho',
        'el hombre araña',
        'harry potter',
        'moby dick',
        'vengadores',
        'avatar',
        'aquaman',
        'el extraterrestre',
        'el mago de oz',
        'blacanieves',
        'la gran aventura lego',
        'la princesa prometida',
        'el gigante de acero',
        'buscando a nemo',
        'oliver',
        'matilda',
        'los increíbles',
        'el ojo mágico',
        'el principito',
        '102 dálmatas',
        'mulan',
        'papá por sorpresa',
        'enredados',
        'el capitán garfio',
        'la espada mágica',
        'mascotas',
        'el planeta del tesoro',
        'buscando a dory',
        'juntos y revueltos',
        'el príncipe de persia',
        'la niñera mágica',
        'mira quien habla',
        'tarzán',
        '50 primeras citas',
      ],
      [
        'payaso',
        'abuela',
        'doctor',
        'vampiro',
        'papá noel',
        'nadador',
        'capitán garfio',
        'bailarín',
        'el grinch',
        'batman',
        'mago',
        'los tres cochinitos',
        'piratas',
        'gigante',
        'harry potter',
        'caperucita roja',
        'pinocho',
        'dumbo',
        'rapunzel',
        'el hombre increíble',
        'lucas',
        'capitán américa',
        'la mujer maravilla',
        'aquaman',
        'el hombre araña',
        'actor',
        'azafata',
        'arquitecto',
        'albañil',
        'astronauta',
        'conductor de autobús',
        'cajera',
        'carpintero',
        'doctor',
        'zapatero',
        'cocinero',
        'químico',
        'dentista',
        'bombero',
        'jardinero',
        'juez',
        'periodista',
        'bibliotecaria',
        'fotógrafo',
        'fontanero',
        'secretaria',
        'mesera',
        'profesora',
        'recepcionista',
        'granjero',
      ],
      [
        'gato',
        'caimán',
        'gallina',
        'vaca',
        'perro',
        'mosquito',
        'tortuga',
        'conejo',
        'pájaro',
        'canguro',
        'mono',
        'culebra',
        'pato',
        'rana',
        'araña',
        'pingüino',
        'puerco',
        'elefante',
        'pez',
        'castor',
        'zorro',
        'leopardo',
        'camello',
        'delfín',
        'caballo',
        'ballena',
        'abeja',
        'águila',
        'avispa',
        'bisonte',
        'búfalo',
        'burro',
        'cangrejo',
        'langosta',
        'caracol',
        'cebra',
        'chimpancé',
        'ciervo',
        'cisne',
        'cocodrilo',
        'escarabajo',
        'escorpión',
        'foca',
        'gallo',
        'hipopótamo',
        'jirafa',
        'león',
        'loro',
        'mosca',
        'oso',
        'oveja',
        'saltamontes',
        'tigre',
        'topo',
        'toro',
      ],
      [
        'correr',
        'bailar',
        'aplaudir',
        'susurrar',
        'jugar escondite',
        'reír',
        'cocinar',
        'batear',
        'saltar',
        'pensar',
        'estornudar',
        'rebotar',
        'saludar',
        'tomar una foto',
        'beber',
        'hacer una taza de té',
        'llamar',
        'jugar juego de video',
        'alcanzar',
        'hacer malabar',
        'llorar',
        'dibujar',
        'lavar el cabello',
        'besar',
        'abrazar',
        'dormir',
        'rezar',
        'cabalgar',
        'peinar',
        'hornear una torta',
        'parpadear',
        'pisar fuerte',
        'patear',
        'cortar el cabello',
        'maquillar',
        'lanzar',
        'ir al baño',
        'subir las escaleras',
        'leer',
        'saltar la cuerda',
        'leer el periódico',
        'bañar al perro',
        'leer la revista',
        'comer pasta',
        'volar',
        'imitar',
        'aspirar',
        'cantar',
        'guiñar',
        'cortar el césped',
        'regar las plantas',
        'toser',
        'detener',
      ],
      [
        'acrobacia',
        'atletismo',
        'billar',
        'culturismo',
        'bolos',
        'ajedrez',
        'dardos',
        'buceo',
        'hípica',
        'pesca',
        'golf',
        'balonmano',
        'senderismo',
        'kung fu',
        'salto de longitud',
        'artes marciales',
        'motociclismo',
        'montañismo',
        'ciclismo de montaña',
        'paracaidismo',
        'parapente',
        'polo',
        'gimnasia rítmica',
        'escalada',
        'correr',
        'vela',
        'buceo',
        'esquí',
        'esnórquel',
        'estiramiento',
        'natación',
        'salto de trampolín',
        'esquí acuático',
        'lucha',
        'carrera de caballos',
        'carrera de carros',
        'salto alto',
        'surfear',
        'yoga',
        'bádminton',
        'aeróbicos',
        'pescar',
        'fútbol',
        'beisbol',
        'tenis',
        'remo',
        'baloncesto',
        'hockey',
        'tiro al arco',
        'patinar',
        'boxeo',
        'esgrima',
        'gimnasia',
        'pesas',
        'ciclismo',
        'triatlón'
      ],
      ['pasó']
    ],
    'en_US': [
      [
        'trumpet',
        'hammer',
        'milk',
        'rocking chair',
        'rocket',
        'airplane',
        'ladder',
        'alarm clock',
        'disco',
        'lunchbox',
        'feet',
        'piano',
        'salt',
        'guitar',
        'ambulance',
        'shoulder',
        'car',
        'tail',
        'baby',
        'braces',
        'shopping cart',
        'stapler',
        'broom',
        'cycle',
        'scissors',
        'hair',
        'balloon',
        'flute',
        'pajamas',
        'rain',
        'earthquake',
        'nose',
        'ice cream cone',
        'glasses',
        'ear',
        'ball',
        'banana peel',
        'hat',
        'ironing board',
        'cheerleader',
        'clock',
        'hair dryer',
        'money',
        'fiddle',
        'chair',
        'telephone',
        'clown',
        'elbow',
        'grandma',
        'doctor',
        'horns',
        'arm',
        'shovel',
        'fire',
        'lollipop',
        'drums',
        'queen',
        'hula hoop',
        'toothbrush',
        'fork',
      ],
      [
        'the little mermaid',
        'puss in boots',
        'planes',
        'monsters inc',
        'cars',
        'hercules',
        'edward scissorhands',
        'mickey mouse',
        'jack and the beanstalk',
        'the lion king',
        'superman',
        'alice in wonderland',
        'cinderella',
        'karate kid',
        "charlotte's web",
        'dumbo',
        'home alone',
        'pinocchio',
        'spider man',
        'harry potter',
        'moby dick',
        'bambi',
        'big fish',
        'the cat in the hat',
        'divergent',
        'doctor dolittle',
        'the duff',
        'every day',
        'flipped',
        'the ghost',
        'nancy drew',
        'heidi',
        'the hobbit',
        'the lord of the ring',
        'the incredible',
        'iron man',
        'jumanji',
        'the jungle book',
        'mary poppins',
        'tiger eyes',
      ],
      [
        'vampire',
        'the easter bunny',
        'zombie',
        'swimmer',
        'captain hook',
        'transformer',
        'dancer',
        'darth vader',
        'the grinch',
        'batman',
        'magician',
        'the three bears',
        'pirates',
        'giant',
        'homer simpson',
        'michael jackson',
        'harry potter',
        'woody',
        'snow white',
        'pinocchio',
        'dumbo',
        'hulk',
        'luke',
        'captain américa',
        'wonder woman',
        'spider man',
        'doctor',
        'elsa',
        'anna',
        'actor',
        'chef',
        'waiter',
        'scientist',
        'dentisit',
        'janitor',
        'firefighter',
        'mario',
        'toad',
        'princess peach',
        'farmer',
        'librarian',
        'bus driver',
        'judge',
        'secretary',
        'cashier',
        'goofy',
        'ursula',
        'simba',
        'baloo',
        'beast',
        'black widow',
        'muppets',
        'peter pan',
        'yoda'
      ],
      [
        'alligator',
        'chicken',
        'cow',
        'dog',
        'mosquito',
        'turtle',
        'rabbit',
        'bird',
        'kangaroo',
        'shark',
        'chimpanzee',
        'snake',
        'duck',
        'cat',
        'frog',
        'spider',
        'penguin',
        'pig',
        'elephant',
        'fish',
        'beaver',
        'fox',
        'cheetah',
        'camel',
        'dolphin',
        'horse',
        'whale',
        'ant',
        'bear',
        'bee',
        'crocodile',
        'deer',
        'eagle',
        'fish',
        'fly',
        'fox',
        'frog',
        'giraffe',
        'goat',
        'goldfish',
        'hamster',
        'hippopotamus',
        'kangaroo',
        'kitten',
        'lion',
        'lobster',
        'monkey',
        'octopus',
        'owl',
        'panda',
        'puppy',
        'rabbit',
        'rat',
        'scorpion',
        'seal',
        'sheep',
        'snail',
        'squirrel',
        'tiger',
        'wolf',
        'zebra',
      ],
      [
        'running',
        'tap dancing',
        'clapping',
        'whispering',
        'hide and seek',
        'giggling',
        'making sandwich',
        'hitting baseball',
        'jumping',
        'thinking',
        'sneezing',
        'bouncing',
        'pinching',
        'waving',
        'taking a selfie',
        'drinking',
        'making a cup of tea',
        'scrolling on a phone',
        'playing video game',
        'cheering',
        'reaching',
        'going on a rollercoaster',
        'juggling',
        'crying',
        'high jump',
        'drawing',
        'washing hair',
        'kissing',
        'hugging',
        'skipping',
        'going to bed',
        'praying',
        'horse riding',
        'brushing hair',
        'baking a cake',
        'winking',
        'stomping',
        'kicking',
        'haircut',
        'putting on makeup',
        'flossing teeth',
        'sprinting',
        'pitching a baseball',
        'farting',
        'going to the bathroom',
        'walking up stairs',
        'reading',
        'jump rope',
        'hiccup',
        'reading the newspaper',
        'washing the dog',
        'reading a magazine',
        'eating spaguetti',
        'flying',
        'miming',
        'hula hooping',
        'cleaning teeth',
        'vacumming',
        'singing karaoke',
        'blinking',
        'mowing the lawn',
        'watering the garden',
        'coughing',
        'stopping',
        'having a nightmare',
      ],
      [
        'rowing',
        'wrestling',
        'horse racing',
        'car racing',
        'high jumping',
        'kayaking',
        'surfing',
        'yoga',
        'badminton',
        'aerobics',
        'ping pong',
        'fishing',
        'soccer',
        'baseball',
        'football',
        'ice hockey',
        'cricket',
        'tennis',
        'hockey sobre hielo',
        'karate',
        'triathlon',
        'golf',
        'ice skating',
        'triathlon',
        'golf',
        'baskeball',
        'swimming',
        'hockey',
        'archery',
        'skateboarding',
        'bowling',
        'boxing',
        'curling',
        'fencing',
        'fitness',
        'gymnastics',
        'volleyball',
        'weightlifting',
        'spinning',
        'olympic swimming',
        'bodyboarding',
        'diving',
        'freediving',
        'paddleboarding',
        'scuba diving',
        'synchronized swimming',
        'judo',
        'kendo',
        'kickboxing',
        'kung fu',
        'marathon',
        'racewalking',
        'sumo',
        'trail running',
        'trampolining',
        'tumbling',
        'walking',
      ],
      ['pass']
    ]
  };

  void remove(String word) {
    _set.remove(word);
  }

  String getPass() {
    int index = _categories[_language].length - 1;
    return _categories[_language][index][0];
  }

  int _generateRandomNumber(int max) {
    var rng = new Random();
    return rng.nextInt(max);
  }

  void resetCategory() {
    print('reset');
    _set = {};
  }

  String getNextWord() {
    var index = _index;
    if (_index == _categories[_language].length - 1)
      index = _generateRandomNumber(_categories.length - 1);

    int size = _categories[_language][index].length;
    String word = _categories[_language][index][_generateRandomNumber(size)];
    if (!_set.contains(word)) {
      _set.add(word);
      return word;
    }
    if (size > _set.length) return getNextWord();

    return null;
  }
}
